/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HoneyPrimeNumbers {
        /**
          * Höchste Zahl bis zu der die Primzahlen ermittelt werden. Für den Wert -1 werden unendlich lang die Primzahlen ermittelt. Auf Grund des trivialen Algorithmus sollte -1 nie verwendet werden. Anderenfalls kommt es zu Speicherüberläufen und Einfrieren des Browsers/Rechners.  ATTENTION: Don't use the value -1 it is only  for damage tests.
         */
        "ende": number;
    }
}
declare global {
    interface HTMLHoneyPrimeNumbersElement extends Components.HoneyPrimeNumbers, HTMLStencilElement {
    }
    var HTMLHoneyPrimeNumbersElement: {
        prototype: HTMLHoneyPrimeNumbersElement;
        new (): HTMLHoneyPrimeNumbersElement;
    };
    interface HTMLElementTagNameMap {
        "honey-prime-numbers": HTMLHoneyPrimeNumbersElement;
    }
}
declare namespace LocalJSX {
    interface HoneyPrimeNumbers {
        /**
          * Höchste Zahl bis zu der die Primzahlen ermittelt werden. Für den Wert -1 werden unendlich lang die Primzahlen ermittelt. Auf Grund des trivialen Algorithmus sollte -1 nie verwendet werden. Anderenfalls kommt es zu Speicherüberläufen und Einfrieren des Browsers/Rechners.  ATTENTION: Don't use the value -1 it is only  for damage tests.
         */
        "ende"?: number;
    }
    interface IntrinsicElements {
        "honey-prime-numbers": HoneyPrimeNumbers;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "honey-prime-numbers": LocalJSX.HoneyPrimeNumbers & JSXBase.HTMLAttributes<HTMLHoneyPrimeNumbersElement>;
        }
    }
}
